# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MatchID', models.CharField(max_length=20)),
                ('PlayerID', models.CharField(max_length=20)),
                ('DScore', models.IntegerField()),
                ('PScore', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='playmatch',
            unique_together=set([('MatchID', 'PlayerID')]),
        ),
    ]
