# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judge',
            old_name='JudgeID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='matchjudge',
            old_name='JudgeID',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='JudgeID',
            new_name='ID',
        ),
        migrations.AlterUniqueTogether(
            name='matchjudge',
            unique_together=set([('MatchID', 'ID')]),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('MatchID', 'ID', 'PlayerID')]),
        ),
    ]
