# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MatchID', models.CharField(max_length=20)),
                ('JudgeID', models.CharField(max_length=20)),
                ('PlayerID', models.CharField(max_length=20)),
                ('Score', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set([('MatchID', 'JudgeID', 'PlayerID')]),
        ),
    ]
