# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='MatchStatus',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
