# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameAdmin', '0002_match_matchstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='playmatch',
            name='AllScore',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='IsScored',
            field=models.BooleanField(default=0),
        ),
    ]
