# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameAdmin', '0002_auto_20171021_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchJudge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MatchID', models.CharField(max_length=20)),
                ('JudgeID', models.CharField(max_length=20)),
                ('IsChief', models.BooleanField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='matchjudge',
            unique_together=set([('MatchID', 'JudgeID')]),
        ),
    ]
