# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameAdmin', '0003_auto_20171212_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobeMatchRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamPlayerPerGroup', models.IntegerField()),
                ('PlayerPerMatch', models.IntegerField()),
                ('PlayerCountInGroupScore', models.IntegerField()),
            ],
        ),
    ]
