# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 05:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameAdmin', '0004_judge_match_player_team_teamcoach_teamleader_teammedic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playmatch',
            name='MatchID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameAdmin.Match'),
        ),
    ]
