# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameAdmin', '0004_globematchrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='MatchType',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
