# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameAdmin', '0005_auto_20171021_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='ChiefID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameAdmin.Judge'),
        ),
        migrations.AlterField(
            model_name='matchjudge',
            name='JudgeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameAdmin.Judge'),
        ),
        migrations.AlterField(
            model_name='matchjudge',
            name='MatchID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameAdmin.Match'),
        ),
        migrations.AlterField(
            model_name='player',
            name='TeamName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameAdmin.Team'),
        ),
        migrations.AlterField(
            model_name='playmatch',
            name='PlayerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameAdmin.Player'),
        ),
        migrations.AlterField(
            model_name='score',
            name='JudgeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameAdmin.Judge'),
        ),
        migrations.AlterField(
            model_name='score',
            name='MatchID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameAdmin.Match'),
        ),
        migrations.AlterField(
            model_name='score',
            name='PlayerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameAdmin.Player'),
        ),
        migrations.AlterField(
            model_name='teamcoach',
            name='TeamName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameAdmin.Team'),
        ),
        migrations.AlterField(
            model_name='teamleader',
            name='TeamName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameAdmin.Team'),
        ),
        migrations.AlterField(
            model_name='teammedic',
            name='TeamName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameAdmin.Team'),
        ),
    ]
