# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameAdmin', '0006_auto_20171021_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='Name',
            new_name='TeamName',
        ),
    ]
