# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameAdmin', '0007_match_subgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='IsScored',
        ),
    ]
