# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-04 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameAdmin', '0008_remove_score_isscored'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Event',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
