# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameAdmin', '0009_player_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='EndTime',
            field=models.CharField(default=2013, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='StartTime',
            field=models.CharField(default=1970, max_length=20),
            preserve_default=False,
        ),
    ]
