# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 00:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameAdmin', '0009_auto_20171026_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamleader',
            name='TeamName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamName+', to='GameAdmin.Team'),
        ),
    ]
