# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-07 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameAdmin', '0010_auto_20180105_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='ScoreAccept',
            field=models.IntegerField(default=0),
        ),
    ]
