# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameAdmin', '0011_auto_20171026_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamleader',
            name='TeamName',
            field=models.ForeignKey(db_column='TeamName', on_delete=django.db.models.deletion.CASCADE, to='GameAdmin.Team'),
        ),
    ]
