# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameAdmin', '0013_auto_20171026_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='CultrueScore',
            new_name='CultureScore',
        ),
    ]
